### ISSUE TITLE
The source cookbook contains more files than your upload

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#91]
Getting this error when trying to upload cookbook with test directory. It's all in git and not listed in .gitignore or chefignore. Any ideas?

```
➜  app-cookbook git:(master) knife cookbook upload app-cookbook --freeze --force

Uploading app-cookbook [0.0.2]
ERROR: Precondition Failed
Response:
=== Cookbook Compare errors found ===
The source cookbook contains more files than your upload:
 - test/integration/default/serverspec/default_spec.rb
 - test/fixtures/data_bags/db/item.json

Source: https://github-enterprise/_codeload/cookbooks/app-cookbook/legacy.tar.gz/master?token=ASD==

Make sure all your changes are merged into the central
repositories before trying to upload the cookbook again.
=====================================

➜  app-cookbook git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by akoldaev** [comment]
Same for .gitignore:

```
=== Cookbook Compare errors found ===
The source cookbook contains more files than your upload:
 - files/default/folder/.gitignore
```

**Comment by akoldaev** [comment]
Just found similar issue https://github.com/xanzy/chef-guard/issues/81

I don't actually want to go through all cookbooks and add files to chefignore, why would chef-guard prevent me from uploading a cookbook here?

**Comment by svanharmelen** [comment]
Because that is exactly what CG is meant to do :wink: It's main job is to make sure that whatever you are trying to upload matches what you have in your git repo.

Now the thing with this specific example is that `knife cookbook upload` uploads only the folders that are known cookbook folders. And `test` isn't one of them so that is causing this error. If your `.gitignore` and `chefignore` are configured correctly this would prevent this kind of errors.

But I see your point and one could argue that CG should only compare all known folders and just ignore the rest... I guess I need to have a detailed look at the internals of Chef server to see what directories are actually stored/saved in the server, and will think about updating the logic of CG to only check those folders instead of the whole repo.

Sound like a logical change but need to think this over a little first...

**Comment by svanharmelen** [comment]
Hi @iroller! I guess that after all this time it's clear that this issue isn't going to get changed/updated and that adding a `chefignore` is the only solution for this problem. So I'm going to close the issue for now. Thanks!
