### ISSUE TITLE
CG should be using correct git username for tagging cookbooks

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#93]
CG uses chef user's name when committing role or data bag change, but when tagging a cookbooks it's always using the name of a user who created a token for CG.

**Comment by svanharmelen** [comment]
Unless it turns out it's a technical limitation of using the Github API (but I don't believe that's the case) this should be labeled as a bug...

**Comment by svanharmelen** [comment]
@iroller is this still an issue? I just checked our own tags and they are all under the user who froze the cookbook. So it seems this works as expected.

**Comment by akoldaev** [comment]
Yes, this is still an issue.

In Github/GithubEnterprise it says the tag author is always the one that created an application key for Chef-guard:

```
iroller created tag v0.2.208 at cookbooks/bc_network  a day ago
a day ago

mdkent pushed to master at cookbooks/bc_network
Matthew Kent
 Matthew Kent 4ba6bc1 Bump to version 0.2.208
 Matthew Kent f389515 New hosts.
View comparison for these 2 commits »
```

However here's `git show v0.2.208` output:

```
tag v0.2.208
Tagger: matt <matt@company.com>
Date:   Wed Aug 5 00:38:50 2015 -0500

Tagged by Chef-Guard

commit 4ba6bc102d577b06a232172bc169c5a51759057a
Author: Matthew Kent <mkent@personal.com>
Date:   Tue Aug 4 22:37:51 2015 -0700

    Bump to version 0.2.208
...
```

Here you can see:
1. Github says tagger is "iroller".
2. Git log shows "matt@company.com" as tagger's email.
3. Git log shows "mkent@personal.com" as commiter's email.
4. Matthew has "matt" login for Chef in organization "company".
5. Matthew has "mdkent" git username and "mkent@personal.com" git email.

So I assume Chef-Guard builds tagger email using Chef username and Chef organization. Shouldn't it be looking into commit author's email? Not sure if it's possible at all.

Related code:
https://github.com/xanzy/chef-guard/blob/dd768c1716c7bc629a5b1890235c8781f67fad87/git.go#L277
https://github.com/xanzy/chef-guard/blob/dd768c1716c7bc629a5b1890235c8781f67fad87/cookbook.go#L258

**Comment by svanharmelen** [comment]
Thanks for the clear explanation!

Your right that CG generates the mail addresses based on the Chef username of the user that is executing the commands in combination with the configured `maildomain` (from the Chef-Guard config file).

In our case this seems to match a 100% of the time as we use AD integration for both the GitHub appliance and our Chef server. So the names will always match up in both locations.

As for the options to look at the commit author's mail, that info is not accessible for Chef-Guard. Chef-Guard will only see an authenticated API call towards your Chef server. So only the Chef username is exposed to Chef-Guard. And of course we could check GitHub for the latest commit, but that does not have to be the same person that is now running `knife cookbook upload ... --freeze`. So it would be wrong to use the name of the person who made the last commit, instead of the name of the user that is actually freezing the cookbook.

The fact that the GitHub log itself shows the owner of the token used by Chef-Guard as the one creating the tag, is completely by design and as expected. We cannot bypass this as it's of course an audit log issue when we could fake the GitHub logging by telling it we are someone else. That would not be a good situation I guess... But luckily the API allows us to pass along info about the (in this case) tagger so that the git log shows the correct user. At least correct from Chef-Guards point of view :wink:

So I think that what we currently do is about the best we can do given the info that we have at that certain point.

**Comment by akoldaev** [comment]
Makes sense, thanks @svanharmelen !
